### ISSUE TITLE
Check Dataset for no spaces between words

### ISSUE THREAD

**Issue by AdamJeddy** [AdamJeddy/Grad-Project-Code#9]
Examples:
your resume howmany page
nextyear school register finish you
you like takecareof plant you

Check on this

**Comment by AdamJeddy** [comment]
It is fine for the ASL
Check preprocessing for English 
ASL: howmany
English: how many

**Comment by AdamJeddy** [comment]
Issue: English sentence doesn't have spaces for words that have one sign (how-many)

**Comment by AdamJeddy** [comment]
![Image](https://user-images.githubusercontent.com/58102753/220363373-a41e281b-0560-4295-8161-4c9dd323f5e4.png)

**Comment by ayeshajr** [comment]
Removed all words which were joined by a '-' in English. e.g. 


![Image](https://user-images.githubusercontent.com/122777235/221903844-eb6a5254-401e-42e2-8203-ebc835785b72.png)
